"use client";

import { Sparkles } from "lucide-react";

interface ReflectionCardProps {
  title?: string;
  content: string;
}

export default function ReflectionCard({
  title = "Today's Reflection",
  content,
}: ReflectionCardProps) {
  return (
    <div className="my-8 flex justify-center">
      <div className="w-full max-w-xl rounded-3xl border border-violet-500/20 bg-gradient-to-br from-violet-500/10 to-fuchsia-500/10 p-6 backdrop-blur-xl">
        <div className="mb-4 flex items-center gap-3">
          <div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-500 to-fuchsia-500">
            <Sparkles size={20} className="text-white" />
          </div>

          <div>
            <h3 className="font-semibold text-white">
              {title}
            </h3>

            <p className="text-xs text-white/45">
              Generated by Meemo
            </p>
          </div>
        </div>

        <p className="leading-8 text-white/80">
          {content}
        </p>
      </div>
    </div>
  );
}